version: '3.8'

services:
  api:
    build: .
    container_name: capstone_api
    ports:
      - "8002:8000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - sqlite_data:/app

  redis:
    image: "redis:alpine"
    container_name: capstone_redis
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    container_name: capstone_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: capstone_grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  sqlite_data:
